### ISSUE TITLE
Lab 5, Task 1, Pipe run error on Database Wallet

### ISSUE THREAD

**Issue by kva-oracle** [oracle-devrel/save-the-wildlife#19]
Hello,

During Lab 5, Task 1, Pipe run an error is presented on Database Wallet, see log snippet below:

2024-02-13T13:40:34.928Z
EXEC: ServiceError:
2024-02-13T13:40:34.928Z
EXEC: {
2024-02-13T13:40:34.929Z
EXEC:     "client_version": "Oracle-PythonSDK/2.119.0, Oracle-PythonCLI/3.37.4",
2024-02-13T13:40:34.929Z
EXEC:     "code": "NotAuthorizedOrNotFound",
2024-02-13T13:40:34.930Z
EXEC:     "logging_tips": "Please run the OCI CLI command using --debug flag to find more debug information.",
2024-02-13T13:40:34.930Z
EXEC:     "message": "Authorization failed or requested resource not found.",
2024-02-13T13:40:34.930Z
EXEC:     "opc-request-id": "XXXXXX",
2024-02-13T13:40:34.930Z
EXEC:     "operation_name": "generate_autonomous_database_wallet",
2024-02-13T13:40:34.931Z
EXEC:     "request_endpoint": "POST https://database.eu-amsterdam-1.oraclecloud.com/20160918/autonomousDatabases/ocid1.autonomousdatabase.oc1.eu-amsterdam-1.<DB_OCID>/actions/generateWallet

**Comment by kva-oracle** [comment]
Hi,

Any updates on this issue?

**Comment by vmleon** [comment]
A full test is done, all working in the Spain region with FRA as a home region.

@kva-oracle, please re-test, and we can follow up.

**Comment by kva-oracle** [comment]
@vmleon: Did a re-run of the whole lab in AMS, all is working now, thank you for the support.
